#!/bin/bash

set -e

if [ $# -le 1 ]; then
    echo "Usage: $0 <isr_gen.c> <isr_gen.inc>"
    exit 1
fi

ISR_GEN_C=$1
ISR_GEN_ASM=$2

ISR_WITH_ERROR_CODE="8 10 11 12 13 14 17 21 29 30"

echo "// This file is autogenerated by generate_isr.sh script!" > $ISR_GEN_C
echo "#include \"idt.h\"" >> $ISR_GEN_C
echo -e "#include \"gdt.h\"\n" >> $ISR_GEN_C

for i in $(seq 0 255); do
    echo "void __attribute__((cdecl)) i686_ISR${i}();" >> $ISR_GEN_C
done

echo -e "\nvoid i686_ISR_InitializeGates () {" >> $ISR_GEN_C

for i in $(seq 0 255); do
    echo "    i686_IDT_SetGate(${i}, i686_ISR${i}, i686_GDT_CODE_SEGMENT, IDT_FLAG_RING_0 | IDT_FLAG_GATE_32BIT_INT);" >> $ISR_GEN_C
done

echo "}" >> $ISR_GEN_C

echo -e "; This file is autogenerated by generate_isr.sh script!\n" > $ISR_GEN_ASM

for i in $(seq 0 255); do
    if echo "$ISR_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
        echo "ISR_ERROR_CODE ${i}" >> $ISR_GEN_ASM
    else
        echo "ISR_NOERROR_CODE ${i}" >> $ISR_GEN_ASM
    fi
done
